### ISSUE TITLE
TypeError: unhashable type: 'types.SimpleNamespace'

### ISSUE THREAD

**Issue by hz963** [shiimizu/ComfyUI_smZNodes#101]
Traceback (most recent call last):
  File "F:\ComfyUI_FK_202408\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_FK_202408\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 18, in 
    PRELOADED_MODULES = init_modules()
                        ^^^^^^^^^^^^^^
  File "F:\ComfyUI_FK_202408\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 9, in init_modules
    return set(modules.values())
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'types.SimpleNamespace'

Cannot import F:\ComfyUI_FK_202408\ComfyUI\custom_nodes\ComfyUI_smZNodes module for custom nodes: unhashable type: 'types.SimpleNamespace'

**Comment by coddz** [comment]
the same error, the patch commited?

Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 18, in <module>
    PRELOADED_MODULES = init_modules()
                        ^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 9, in init_modules
    return set(modules.values())
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'types.SimpleNamespace'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes module for custom nodes: unhashable type: 'types.SimpleNamespace'
