### ISSUE TITLE
ERROR  AttributeError: 'SDClipModel' object has no attribute 'unhook'

### ISSUE THREAD

**Issue by 1272870698** [shiimizu/ComfyUI_smZNodes#104]
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! 'SDClipModel' object has no attribute 'unhook'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 192, in HijackClip
    text_processing_engine = ClassicTextProcessingEngine(
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\text_processing\classic_engine.py", line 85, in __init__
    self.id_pad = self.pad_token
AttributeError: 'ClassicTextProcessingEngine' object has no attribute 'pad_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 98, in encode
    with HijackClip(clip, opts) as clip:
  File "F:\SD\sd-webui-aki-v4.5\python\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 205, in HijackClip
    getattr(inner_store[a2[0]], a2[1]).__self__.unhook()
  File "F:\SD\sd-webui-aki-v4.5\python\lib\site-packages\torch\nn\modules\module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SDClipModel' object has no attribute 'unhook'

**Comment by shiimizu** [comment]
What checkpoint did you use?

**Comment by acorderob** [comment]
Bumping, since i just got `'Qwen25_7BVLIModel' object has no attribute 'unhook'` (Qwen workflow). Same thing happens with 'Qwen3_4BModel' (ZIT workflow).

<img width="252" height="109" alt="Image" src="https://github.com/user-attachments/assets/99936e5c-9e74-41eb-9836-9fbe27012343" />

<img width="264" height="125" alt="Image" src="https://github.com/user-attachments/assets/06cc1b2f-ae42-4990-aca7-d389cbfb248a" />
