### ISSUE TITLE
TypeError: unhashable type: 'types.SimpleNamespace' after patching #102

### ISSUE THREAD

**Issue by coddz** [shiimizu/ComfyUI_smZNodes#105]
after patching #102 , the unhashable error alse appears.

the newest comfyui + tortch2.4.1+cu12.4 (comfyui release version 0.22)

Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 19, in <module>
    PRELOADED_MODULES = init_modules()
                        ^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 10, in init_modules
    return set([m for m in modules.values() if not isinstance(m, types.ModuleType)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'types.SimpleNamespace'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes module for custom nodes: unhashable type: 'types.SimpleNamespace'

**Comment by shiimizu** [comment]
Thanks for the report. It should be fixed now.

**Comment by coddz** [comment]
Thank shiimizu. Just ok when I add the new patch.
