### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by za-wa-n-go** [shiimizu/ComfyUI_smZNodes#15]
After the latest update to ComfyUI today, I am getting the following error
This was not a problem on the 26th, so the update on the 27th seems to have affected the issue.

Traceback (most recent call last):
  File "C:\Product\ComfyUI\nodes.py", line 1733, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 91, in <module>
    KSampler.sample = inject_code(KSampler.sample, payload)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Product\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 954, in inject_code
    raise FileNotFoundError
FileNotFoundError

**Comment by shiimizu** [comment]
Should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/8de4bb46b5f10afb9793a16e99d40c27b24e7a76

**Comment by shiimizu** [comment]
Should be fixed in the latest commit (https://github.com/shiimizu/ComfyUI_smZNodes/commit/8de4bb46b5f10afb9793a16e99d40c27b24e7a76).
