### ISSUE TITLE
Error after last update - no attribute 'sampler'

### ISSUE THREAD

**Issue by Suzie1** [shiimizu/ComfyUI_smZNodes#16]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1748, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 99, in <module>
    _Sampler = comfy.samplers.Sampler
AttributeError: module 'comfy.samplers' has no attribute 'Sampler'

**Comment by shiimizu** [comment]
Should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/f873c6c60e473fdf74aa21d42da7730d1d8a3786.
