### ISSUE TITLE
NO attribute 'CrossAttentionPytorch'

### ISSUE THREAD

**Issue by Piscabo** [shiimizu/ComfyUI_smZNodes#21]
Fail to Load Nodes:
**### ComfyUI Revision: 1561 [536799d1] | Released on '2023-10-11'**

Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 48, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 6, in <module>
    from .modules.sd_hijack import model_hijack
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack.py", line 8, in <module>
    from . import devices, shared, sd_hijack_unet, sd_hijack_optimizations, script_callbacks, errors
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_unet.py", line 38, in <module>
    from . import sd_hijack_optimizations
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_optimizations.py", line 22, in <module>
    ldm.modules.attention.CrossAttentionPytorch,
AttributeError: module 'comfy.ldm.modules.attention' has no attribute 'CrossAttentionPytorch'

Cannot import A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_smZNodes module for custom nodes: module 'comfy.ldm.modules.attention' has no attribute 'CrossAttentionPytorch'

**Comment by tgutierrez** [comment]
Disclaimer: I have no idea what I'm really doing.

I managed to get around this by removing lines 22 and 23 on this file: https://github.com/shiimizu/ComfyUI_smZNodes/blame/main/modules/sd_hijack_optimizations.py

On your install, this is under  /custom_nodes/ComfyUI_smZNodes/modules

Deleting those two lines and saving seems to fix the issue.

Be aware that you might need to do a `git checkout .` or `git reset --hard` if this is fixed on this node pack.

**Comment by shiimizu** [comment]
Should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/cf613fd1c44dda91a7debc963557adbb38705733
