### ISSUE TITLE
Empty module name

### ISSUE THREAD

**Issue by rickcx** [shiimizu/ComfyUI_smZNodes#3]
Traceback (most recent call last):
  File "/home/bob/ComfyUI/nodes.py", line 1604, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI_smZNodes/__init__.py", line 69, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI_smZNodes/nodes.py", line 3, in <module>
    from .modules.sd_hijack import model_hijack, list_optimizers
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI_smZNodes/modules/sd_hijack.py", line 9, in <module>
    from . import devices, shared, sd_hijack_unet, sd_hijack_optimizations, script_callbacks, errors
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI_smZNodes/modules/sd_hijack_unet.py", line 129, in <module>
    CondFunc('open_clip.transformer.ResidualAttentionBlock.__init__', lambda orig_func, *args, **kwargs: kwargs.update({'act_layer': GELUHijack}) and False or orig_func(*args, **kwargs), lambda _, *args, **kwargs: kwargs.get('act_layer') is None or kwargs['act_layer'] == torch.nn.GELU)
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI_smZNodes/modules/sd_hijack_utils.py", line 10, in __new__
    resolved_obj = importlib.import_module('.'.join(func_path[:i]))
  File "/home/bob/anaconda3/envs/ComfyUI/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1047, in _gcd_import
  File "<frozen importlib._bootstrap>", line 981, in _sanity_check
ValueError: Empty module name

Cannot import /home/bob/ComfyUI/custom_nodes/ComfyUI_smZNodes module for custom nodes: Empty module name

**Comment by shiimizu** [comment]
Thanks for the stacktrace :)
It should work now in the latest commit. The error also goes away by installing `open-clip-torch`.
