### ISSUE TITLE
Error with get_steps when steps input of KSampler is converted to input

### ISSUE THREAD

**Issue by Dystasia** [shiimizu/ComfyUI_smZNodes#36]
Hi,

When converting the steps of the nearest KSampler to the smZNodes to input comfy throws the following error:

> [ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "C:\Users\username\ComfyUI_windows_portable\ComfyUI\server.py", line 633, in trigger_on_prompt
    json_data = handler(json_data)
  File "C:\Users\username\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 824, in prompt_handler
    tmp()
  File "C:\Users\username\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 819, in tmp
    steps = find_nearest_ksampler(clip_id)
  File "C:\Users\username\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 769, in find_nearest_ksampler
    return get_steps(data, ksampler_id)
  File "C:\Users\username\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 781, in get_steps
    return min(max(1, int(steps_input_value)), 10000)
ValueError: invalid literal for int() with base 10: ''

Converting it back to a widget makes the error go away.

I have multiple KSamplers and other detailers that I want to use an input steps with, so it is a pain having to change them all manually just for this node.

**Comment by Rvage0815** [comment]
looks like the error is still present got almost the same:

> [ERROR] An error occurred during the on_prompt_handler processing
> Traceback (most recent call last):
>   File "D:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 770, in trigger_on_prompt
>     json_data = handler(json_data)
>                 ^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 656, in prompt_handler
>     steps = find_nearest_ksampler(clip_id)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 585, in find_nearest_ksampler
>     return get_val(data, ksampler_id, steps_validator, 'steps')
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 601, in get_val
>     return min(max(1, int(steps_input_value)), 10000)
>                       ^^^^^^^^^^^^^^^^^^^^^^
> ValueError: invalid literal for int() with base 10: 'lcm'

if you need the steps i would suggest to add an int input so we can send the steps to the node^^ with ue or direct connection
