### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by alenknight** [shiimizu/ComfyUI_smZNodes#38]
updated to latest nodes for smZNodes - and getting the index out of range error when using  CLIPTEXTENCODE++
![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/22153900/7c8891d1-427d-4762-b2e5-be4284d1b9b3)

(with A1111 parser.  the comfy parser works)

![image](https://github.com/shiimizu/ComfyUI_smZNodes/assets/22153900/3d9c48ca-b604-419b-ad9f-bbe05aff5dac)

here's my terminal logs
```
C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --listen --windows-standalone-build
** ComfyUI start up time: 2023-12-07 13:20:30.891833

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\AI\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\AI\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\AI\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\AI\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\AI\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\AI\stable-diffusion-webui\models/ControlNet
Web extensions folder found at C:\AI\ComfyUI\ComfyUI\web\extensions\ComfyLiterals
### Loading: ComfyUI-Impact-Pack (V4.38.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
### Loading: ComfyUI-Inspire-Pack (V0.47.3)
### Loading: ComfyUI-Manager (V1.7.2)
### ComfyUI Revision: 1791 [248d9125] | Released on '2023-12-07'
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
skbuild is already installed.

[SD Prompt Reader] Node version: 1.1.0
[SD Prompt Reader] Core version: 1.3.4b2
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Comfyroll Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Davemane42 Custom Nodes: Loaded
FizzleDorf Custom Nodes: Loaded
Using xformers cross attention
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
C:\AI\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
C:\AI\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions
C:\AI\ComfyUI\ComfyUI\custom_nodes\NodeGPT\AutoUpdate.json
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\NodeGPT\llava.py", line 9, in <module>
    from llama_cpp.llama_chat_format import Llava15ChatHandler
ModuleNotFoundError: No module named 'llama_cpp.llama_chat_format'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\NodeGPT\__init__.py", line 127, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\NodeGPT\llava.py", line 24, in <module>
    from llama_cpp.llama_chat_format import Llava15ChatHandler
ModuleNotFoundError: No module named 'llama_cpp.llama_chat_format'

Cannot import C:\AI\ComfyUI\ComfyUI\custom_nodes\NodeGPT module for custom nodes: No module named 'llama_cpp.llama_chat_format'
[Power Noise Suite]: 🦚🦚🦚 Squaaack! 🦚🦚🦚
[Power Noise Suite]: Tamed 11 wild nodes.

[rgthree] Loaded 18 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

Searge-SDXL v4.3.1 in C:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Art is the mirror that reflects the beauty within us." - Unknown


Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Nk_vaeswitch.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Nk_imgInputSwitch3Way.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\image_to_contrast_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\imageflip_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\NK_4way Image Switch_v2.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\brightness_contrast_ally_modified.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\brightness_contrast_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\histogram_equalization.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\invert_image_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\image_to_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\monocromatic_clip_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\gaussian_blur_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\mosaic_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Kohya_hiResFix.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\invert_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Pseudo_HDR_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\saturation_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Nk_4way Latent Switch.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sharpness_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\vae_decode_preview.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\crop_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\gaussian_blur_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Mile-High-Styler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledIPAdapter
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-previewlatent
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_NoxinNodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\cg_custom_core
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\PowerNoiseSuite
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-plasma
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler-main
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.3 seconds (IMPORT FAILED): C:\AI\ComfyUI\ComfyUI\custom_nodes\NodeGPT
   0.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\clipseg.py
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   0.6 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.7 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL
   1.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
QualityOfLifeSuit_Omar92::NSP ready
FETCH DATA from: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
ERROR:root:Failed to validate prompt for output 999:
ERROR:root:* Saturation 998:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 1020:
ERROR:root:* ImageCASharpening+ 994:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 1004:
ERROR:root:* Brightness & Contrast modded 1000:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 984:
ERROR:root:* Gaussian Blur 983:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
Requested to load SD1ClipModel
Loading 1 new model
----------------------------------------
Efficient Loader Models Cache:
Ckpt:
  [1] realisticVisionV60B1_v60B1VAE
Lora:
  [1] base_ckpt: realisticVisionV60B1_v60B1VAE
      lora(mod,clip): oversized_fur-10(0.2,0.25)
      lora(mod,clip): breastsizeslideroffset(-0.05,1)
      lora(mod,clip): muscle_slider_v1(1.6,1)
      lora(mod,clip): more_details(0.2,1)
      lora(mod,clip): add_detail(0.2,1)
      lora(mod,clip): detail_slider_v4(0.2,1)
      lora(mod,clip): Biomechanicals_v2_lora1500_HRGIGER(0.35,0.5)
      lora(mod,clip): edgWar40kCommissarv1(0.75,1)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 148, in encode_with_transformers_comfy_
    z, pooled = ClipTextEncoderCustom._forward(self.wrapped, tokens) # self.wrapped.encode(tokens)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 97, in _forward
    dtype = getattr(self.transformer, self.inner_name, self.transformer.text_model).final_layer_norm.weight.dtype
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SDClipModel' object has no attribute 'inner_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 86, in encode
    result = run(**params)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 714, in run
    cond, pooled = clip_clone.encode_from_tokens(tokens, True)
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 131, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 440, in encode_token_weights
    else:       schedules = prompt_parser.get_learned_conditioning(model_hijack.cond_stage_model, texts, steps, None, opts.use_old_scheduling)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\prompt_parser.py", line 202, in get_learned_conditioning
    conds = model.forward(texts)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_clip.py", line 206, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_clip.py", line 235, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 249, in encode_with_transformers
    return self.encode_with_transformers_comfy_(tokens, return_pooled)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 150, in encode_with_transformers_comfy_
    z, pooled = ClipTextEncoderCustom._forward(self.wrapped, tokens_orig)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 93, in _forward
    tokens = self.set_up_textual_embeddings(tokens, backup_embeds)
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 131, in set_up_textual_embeddings
    if y.shape[0] == current_embeds.weight.shape[1]:
IndexError: tuple index out of range

Prompt executed in 4.75 seconds
got prompt
ERROR:root:Failed to validate prompt for output 999:
ERROR:root:* Saturation 998:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 1020:
ERROR:root:* ImageCASharpening+ 994:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 1004:
ERROR:root:* Brightness & Contrast modded 1000:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 984:
ERROR:root:* Gaussian Blur 983:
ERROR:root:  - Required input is missing: image
ERROR:root:Output will be ignored
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 148, in encode_with_transformers_comfy_
    z, pooled = ClipTextEncoderCustom._forward(self.wrapped, tokens) # self.wrapped.encode(tokens)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 97, in _forward
    dtype = getattr(self.transformer, self.inner_name, self.transformer.text_model).final_layer_norm.weight.dtype
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SDClipModel' object has no attribute 'inner_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 86, in encode
    result = run(**params)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 714, in run
    cond, pooled = clip_clone.encode_from_tokens(tokens, True)
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 131, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 439, in encode_token_weights
    if multi:   schedules = prompt_parser.get_multicond_learned_conditioning(model_hijack.cond_stage_model, texts, steps, None, opts.use_old_scheduling)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\prompt_parser.py", line 281, in get_multicond_learned_conditioning
    learned_conditioning = get_learned_conditioning(model, prompt_flat_list, steps, hires_steps, use_old_scheduling)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\prompt_parser.py", line 202, in get_learned_conditioning
    conds = model.forward(texts)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_clip.py", line 206, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_clip.py", line 235, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 249, in encode_with_transformers
    return self.encode_with_transformers_comfy_(tokens, return_pooled)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 150, in encode_with_transformers_comfy_
    z, pooled = ClipTextEncoderCustom._forward(self.wrapped, tokens_orig)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 93, in _forward
    tokens = self.set_up_textual_embeddings(tokens, backup_embeds)
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 131, in set_up_textual_embeddings
    if y.shape[0] == current_embeds.weight.shape[1]:
IndexError: tuple index out of range

Prompt executed in 0.14 seconds
```

**Comment by shiimizu** [comment]
It should be fixed in https://github.com/shiimizu/ComfyUI_smZNodes/commit/89c467d75b2cf1a9b593e1c273cfe8f96e846307.

**Comment by MalikKillian** [comment]
I think https://github.com/shiimizu/ComfyUI_smZNodes/commit/89c467d75b2cf1a9b593e1c273cfe8f96e846307 improved the situation but I now have an error on smZ Settings:

```
Error occurred when executing smZ Settings:

tuple index out of range

File "C:\Users\MalikKillian\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\MalikKillian\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\MalikKillian\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\MalikKillian\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 164, in run
clip = kwargs.pop('clip', None) if 'clip' in kwargs else args[0]
~~~~^^^
```

Originally I attached smZ Settings to a MODEL link. Switching it to CLIP didn't seem to help.

**Comment by MalikKillian** [comment]
Ah, nevermind. Comfy doesn't refresh the node when it's updated. Now that I'm using the updated smZ Settings that requires a CLIP input things are working again.

**Comment by alenknight** [comment]
thanks this works now!
