### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by githabtane** [shiimizu/ComfyUI_smZNodes#74]
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 55, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\nodes.py", line 6, in <module>
    from .modules import prompt_parser, devices, shared
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\prompt_parser.py", line 12, in <module>
    from .shared import opts, log
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\shared.py", line 27, in <module>
    opts.upcast_attn = not args.dont_upcast_attention
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'dont_upcast_attention'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes module for custom nodes: 'Namespace' object has no attribute 'dont_upcast_attention'

**Comment by Autantpourmoi** [comment]
Exactly same error message since last update of the nodes
