### ISSUE TITLE
[Error] T2I-Adapter Style affects.

### ISSUE THREAD

**Issue by za-wa-n-go** [shiimizu/ComfyUI_smZNodes#8]
It seems that when I add smZNodes, I can't use T2I-Adapter's Style.
The following error occurs, and when smZNodes is disabled, it works fine.
Sorry, but could you please address this issue as I would like to use both.

```
!!! Exception during processing !!!
Traceback (most recent call last):
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\nodes.py", line 787, in load_style_model
style_model = comfy.sd.load_style_model(style_model_path)
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\comfy\sd.py", line 261, in load_style_model
model = comfy.t2i_adapter.adapter.StyleAdapter(width=1024, context_dim=768, num_head=8, n_layes=3, num_token=8)
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\comfy\t2i_adapter\adapter.py", line 203, in init
self.transformer_layes = nn.Sequential([ResidualAttentionBlock(width, num_head) for _ in range(n_layes)])
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\comfy\t2i_adapter\adapter.py", line 203, in <listcomp>
self.transformer_layes = nn.Sequential([ResidualAttentionBlock(width, num_head) for _ in range(n_layes)])
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_utils.py", line 17, in <lambda>
setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_utils.py", line 26, in call
return self.__sub_func(self.__orig_func, *args, **kwargs)
File "C:\Product\StabilityMatrix-win-x64\Data\Packages\ComfyUI_Matrix\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_unet.py", line 122, in <lambda>
CondFunc('comfy.t2i_adapter.adapter.ResidualAttentionBlock.init', lambda orig_func, *args, **kwargs: kwargs.update({'act_layer': GELUHijack}) and False or orig_func(*args, **kwargs), lambda _, *args, **kwargs: kwargs.get('act_layer') is None or kwargs['act_layer'] == torch.nn.GELU)
TypeError: ResidualAttentionBlock.init() got an unexpected keyword argument 'act_layer'
```

**Comment by shiimizu** [comment]
Thanks for the report :)
Although the T2I-Adapters were working for me, the latest commit  (https://github.com/shiimizu/ComfyUI_smZNodes/commit/5334f3e4c1cdbd7a3660abc33569bc480857114f) should make it work for everyone else.

**Comment by za-wa-n-go** [comment]
thankyou!!
